### ISSUE TITLE
POST /engines/<engineID>/queries always returning empty result

### ISSUE THREAD

**Issue by joetex** [actionml/harness#266]
Using the latest harness:develop docker build has an issue calling ElasticSearch when using the harness API for queries.  

I tested using elasticsearch:5.6, elasticsearch:6.8.12, and the default elasticsearch:7.6.0.  

The issue seems to be in the ElasticSearchSupport.scala in the search or searchAsync functions, as it is hitting 
 ```scala
case _ => Seq.empty[Hit]
```
or 
```scala
case _ =>
              logger.trace(s"Query: $query\nproduced status code: ${response.getStatusLine.getStatusCode}")
              p.complete(Success(Seq.empty[Hit]))
```
I am unable to turn on TRACE or DEBUG logging in the harness container's `conf/logback.xml` file (feature request?), so I've come to this conclusion from looking at source code and always getting this result:
```
{
  "result": []
}
```

P.s. I can successfully query and get results from ES directly using: 

localhost:9200/_alias/trainingb

localhost:9200/trainingb_[randnum]/_search

Thanks,

Joel

**Comment by joetex** [comment]
I installed Harness natively, and was able to change logging to use TRACE level.  Below is the query request JSON body to ElasticSearch being performed behind the scenes:

You will notice that it has a filter range for `timeexpired` and `timeinserted` at the exact same dates of today.  These filters to ES should not be used unless explicitly specified in the Harness API /queries.  I have those date fields specified in my Engine Config JSON.

```
{
  "size": 20,
  "from": 0,
  "query": {
    "bool": {
      "must": {
        "match_all": {
          "boost": 0
        }
      },
      "must_not": [],
      "filter": [
        {
          "range": {
            "timeexpired": {
              "gt": "2020-09-04T18:19:29.542Z"
            }
          }
        },
        {
          "range": {
            "timeinserted": {
              "lt": "2020-09-04T18:19:29.543Z"
            }
          }
        }
      ],
      "should": []
    }
  },
  "sort": [
    {
      "_score": {
        "order": "desc"
      }
    },
    {
      "popRank": {
        "unmapped_type": "double",
        "order": "desc"
      }
    }
  ]
}
```

**Comment by pferrel** [comment]
As noted on the Google group

I see. No, not a bug. You are using two methods of datetime filtering together. One uses a datetime in each item and a range in the query but the other compares 2 times in the item with the server time. It is unlikely that you have item properties set to satisfy both filters.

docs for our legacy PIO version that still applies. https://actionml.com/docs/ur_queries

You generally should not specify all of these:
"expireDateName": "timeexpired",
"availableDateName": "timeinserted",
"dateName": "timeupdated"

What would you like to do?

1) put a datetime in the objects and range in query? Then specify only the name of the item property that you want the query range to bracket. So specify only  “dateName”.

2) you want 2 datetimes in the item to bracket the server’s datetime, specify availableDateName and expireDateName then do nothing in the query. These properties must be set in every item that you want to be considered for recs. Since this requires nothing in the query it is the datetime filter that is goiving you trouble so remove these properties from config.

As you can see these are two separate methods and should not be mixed unless you think through the interactions very carefully.

BTW the image tag will tell you which github commit is used to create any image, see hub.docker for a description of available tags. The sample docker-compose setup uses the most recent code from the “develop” branch but you can pin it to any of the available tags, like the “latest” release.

**Comment by pferrel** [comment]
This is an issue with our documentation at least. 

Moved here: https://github.com/actionml/docs.actionml.com/issues/20
